recycling-server/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'users/:id', action: :show, controller: 'profile'

  get 'developers/index'
  get 'search/index'
  get 'welcome/index'
  get 'download', to: 'welcome#download'

  resources :cities

  resources :categories

  resources :media_contents, only: [:create]

  root 'welcome#index'

  # API V1
  get 'api/v1/cities',                   action: :get_cities,              controller: 'cities_api'
  get 'api/v1/cities/:id',               action: :get_city_by_id,          controller: 'cities_api'
  get 'api/v1/cities/:id/categories',    action: :get_categories_by_id,    controller: 'cities_api'
  get 'api/v1/cities/:id/subcategories', action: :get_subcategories_by_id, controller: 'cities_api'
  get 'api/v1/cities/:id/facilities',    action: :get_facilities,          controller: 'cities_api'

end

recycling-server/app/models/city.rb
require 'elasticsearch/model'

class City < ApplicationRecord
  # Define associations
  has_many :recycles
  has_many :subcategories, through: :recycles
  has_many :has_facilities
  has_many :facilities, through: :has_facilities
  has_many :city_contacts

  accepts_nested_attributes_for :recycles
  accepts_nested_attributes_for :facilities
  accepts_nested_attributes_for :city_contacts

  # Define uploader
  mount_uploader :image_link, MediaUploader
  mount_uploaders :files, MediaUploader

  # Search prereq
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name "cities-#{Rails.env}-index"

  def self.search(query)
    __elasticsearch__.search({
        query: {
            multi_match: {
                query: query,
                fields: [ "name^3", "zipcode"],
                fuzziness: 2
            }
        },
        highlight: {
            pre_tags: ['<mark>'],
            post_tags: ['</mark>'],
            fields: { name: {}, zipcode: {} }
        },
        suggest: {
            text: query,
            name: {
                term: { size: 1, field: :name }
            },
            zipcode: {
                term: { size: 1, field: :zipcode }
            }
        }
    })
  end

  def self.find_subcategories_by_id(city_id, category_id)
    city = City.find_by_id(city_id)
    city.subcategories.where(category_id: category_id)
  end

  def self.find_facilities_by_city(city_id)
    city = City.find_by_id(city_id)
    city.facilities.all
  end

  def self.find_contributor_by_id(city_id)
    city = City.find_by_id(city_id)
    User.find_by_id(city.uid)
  end

  def self.find_category_ids(city_id)
    city = City.find_by_id(city_id)
    categories = []
    city.subcategories.each do |subcategory|
      unless categories.include?(subcategory.category_id)
        categories.push(subcategory.category_id)
      end
    end
    categories

  end
end

unless City.__elasticsearch__.index_exists?
  City.__elasticsearch__.create_index!
  City.import
end

recycling-server/app/models/facility.rb
class Facility < ApplicationRecord
    has_many :facility_recycles
    has_many :categories, through: :facility_recycles
    has_many :has_facilities
    has_many :cities, through: :has_facilities
end

recycling-server/app/controllers/cities_controller.rb
require 'elasticsearch/model'
require 'json'

class CitiesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def index

  end

  def show
    @city = City.find_by_id(params[:id])
    @categories = Category.all
    @filesJSON = @city.files
    @contributor = City.find_contributor_by_id(@city.id)
  end

  def new
    if current_user.city_id != nil
      redirect_to "/cities/#{current_user.city_id}"
    end

    @city = City.new
    @city.facilities.build
    @city.city_contacts.build

    @categories = Category.all
  end

  def edit
    @city = City.find_by_id(params[:id])
    @categories = Category.all
    @category_ids = City.find_category_ids(params[:id])
  end

  def create
    @city = City.new(permit_city)

    if @city.save
      # Update user city
      current_user.update_attributes(city_id: @city.id)

      # Construct subcategories and save them to recycles
      Category.all.each do |category|
        params[:city][:recycle]["#{category.id}"].each do |subcategory_id|
          if subcategory_id.present?
            @recycle = Recycle.new({ :city_id => @city.id,
                                     :subcategory_id => subcategory_id })
            unless @recycle.save
              flash[:error] = @city.errors.full_messages
              redirect_to new_city_path
            end
          end
        end
      end

      flash[:success] = "Success!"
      redirect_to city_path(@city)

    else
      flash[:error] = @city.errors.full_messages
      redirect_to new_city_path
    end
  end

  def update
    @city = City.find_by_id(params[:id])
    # @facilities = @city.facilities

    if @city.update(permit_city)
      Recycle.where(city_id: @city.id).delete_all

      Category.all.each do |category|
        params[:city][:recycle]["#{category.id}"].each do |subcategory_id|
          if subcategory_id.present?
            @recycle = Recycle.new({ :city_id => @city.id,
                                     :subcategory_id => subcategory_id })
            unless @recycle.save
              flash[:error] = @city.errors.full_messages
              redirect_to edit_city_path(@city)
            end
          end
        end
      end

      flash[:success] = "Success!"
      redirect_to city_path(@city)
    else
      puts @city.errors.full_messages
      flash[:error] = @city.errors.full_messages
      redirect_to edit_city_path(@city)
    end
  end

  private

  def permit_city
    params.require(:city).permit(:uid,
                                 :name,
                                 :state,
                                 :zipcode,
                                 :website,
                                 :description,
                                 :image_link,
                                 {
                                   files: [],
                                   city_contacts_attributes: [
                                     :id,
                                     :name,
                                     :contact
                                   ],
                                   facilities_attributes: [
                                     :id,
                                     :name,
                                     :street_address,
                                     :website
                                   ]
                                 })
  end
end
 

recycling-server/app/helpers/cities_helper.rb
module CitiesHelper
end

recycling-server/app/views/cities/edit.html.erb
<%= render partial: "layouts/nav", locals: {items: ["Contact"], shouldShow: true, shouldShowDevelopers: false, useFixedNav: true} %>

<section class="city-new-container">
  <div class="col-10 col-sm-10 col-md-6 col-offset-1 col-sm-offset-1 col-md-offset-3">
    <div class="text-center">
      <h2 class="section-heading">Edit info for <%= @city.name %></h2>
      <hr class="primary">
    </div>

    <div class="city-form-container form-horizontal">
      <%= form_for(@city) do |f| %>
          <input name="_method" type="hidden" value="patch" />

          <div class="form-group">
            <%= f.label(:name, 'Name: ', class: 'col-sm-2 control-label item') %>
            <div class="col-sm-10">
              <%= f.text_field(:name, { :class => 'form-control', :placeholder => 'Name of the city', :value => @city.name }) %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label(:state, 'State: ', class: 'col-sm-2 control-label item') %>
            <div class="col-10 col-sm-4 col-md-4">
              <%= f.text_field(:state, { :class => 'form-control', :placeholder => 'State of the city', :value => @city.state }) %>
            </div>

            <%= f.label(:zipcode, 'Zipcode: ', class: 'col-sm-2 control-label item') %>
            <div class="col-10 col-sm-4 col-md-4">
              <%= f.text_field(:zipcode, { :class => 'form-control', :placeholder => 'Zipcode of the city', :value => @city.zipcode }) %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label(:website, 'Website: ', class: 'col-sm-2 control-label item') %>
            <div class="col-sm-10">
              <%= f.text_field(:website, { :class => 'form-control', :placeholder => 'Website url for the city recycling info page', :value => @city.website }) %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag(:description, 'Description: ', class: 'col-sm-2 control-label item') %>
            <div class="col-sm-10">
              <%= f.text_area(:description,
                              { :rows => 5, :class => 'form-control', :placeholder => 'A short description of the city', :value => @city.description }) %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag(:categories, 'Categories: ', class: 'col-sm-2 control-label item') %>
            <div class="col-sm-10">
              <%= select_tag('category', options_for_select(@categories.map { |category| [category.name, category.id] }, @category_ids),
                             { :multiple => true,
                               :'data-placeholder' => 'Choose categories...',
                               :include_blank => true,
                               :class => "chosen-select-category" })
              %>
            </div>
          </div>

          <% @categories.each do |category| %>
              <div class="form-group subcategory-selector <%= (@category_ids.include?(category.id)) ? 'active' : '' %>" id="subcategory-selector-<%= category.id %>">
                <%= f.fields_for :recycle do |recycle_form| %>
                    <%= label_tag(category.id, "Subcategories for #{category.name}:", class: 'col-sm-2 control-label item') %>
                    <div class="col-sm-10">
                      <%= recycle_form.collection_select(category.id, category.subcategories, :id, :name,
                                                         options = { :selected => @city.subcategories.where(category_id: category.id).map { |s| s.id } },
                                                         html_options = {
                                                            :multiple => true,
                                                            :'data-placeholder' => "Choose subcategories for #{category.name.downcase}...",
                                                            :include_blank => true,
                                                            :class => 'chosen-select-subcategory',
                                                         })
                      %>
                    </div>
                <% end %>
              </div>
          <% end %>

          <div class="form-group">
            <%= label_tag :facilities, 'Facilities: ', class: 'col-sm-2 control-label item' %>
            <div class="col-sm-10">
              <div class="row clearfix">
                <div class="col-md-12 column">
                  <input type="hidden" id="num-facilities" value="<%= @city.facilities.length %>" />
                  <table class="table table-bordered" id="facilities-table">
                    <thead>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Name</th>
                      <th class="text-center">Address</th>
                      <th class="text-center">Website</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @city.facilities.each_with_index do |facility, index| %>
                        <input type="hidden"
                               id='city_facilities_attributes_<%= index %>_id'
                               name='city[facilities_attributes][<%= index %>][id]'
                               value="<%= facility.id %>">
                        <tr id='facility-<%= index %>'>
                          <td><%= index + 1 %></td>
                          <td>
                            <input type="text"
                                   id='city_facilities_attributes_<%= index %>_name'
                                   name='city[facilities_attributes][<%= index %>][name]'
                                   placeholder='Name' value="<%= facility.name %>" class='form-control input-md'>
                          </td>
                          <td>
                            <input type="text"
                                   id='city_facilities_attributes_<%= index %>_street_address'
                                   name='city[facilities_attributes][<%= index %>][street_address]'
                                   placeholder='Address' value="<%= facility.street_address %>" class='form-control input-md'>
                          </td>
                          <td>
                            <input type="text"
                                   id='city_facilities_attributes_<%= index %>_website'
                                   name='city[facilities_attributes][<%= index %>][website]'
                                   placeholder='Website' value="<%= facility.website %>" class='form-control input-md'>
                          </td>
                        </tr>
                    <% end %>
                    <tr id='facility-<%= @city.facilities.length %>'></tr>
                    </tbody>
                  </table>
                </div>
                <button type="button" id='delete-facility' class="pull-right btn btn-default">Delete Facility</button>
                <button type="button" id="add-facility" class="pull-right btn btn-default">Add Facility</button>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :city_contacts, 'Additional Contacts: ', class: 'col-sm-2 control-label item' %>
            <div class="col-sm-10">
              <div class="row clearfix">
                <div class="col-md-12 column">
                  <input type="hidden" id="num-contacts" value="<%= @city.city_contacts.length %>" />
                  <table class="table table-bordered" id="contacts-table">
                    <thead>
                    <tr>
                      <th class="text-center">#</th>
                      <th class="text-center">Name</th>
                      <th class="text-center">Email/Phone</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @city.city_contacts.each_with_index do |contact, index| %>
                    <input type="hidden"
                           id='city_city_contacts_attributes_<%= index %>_id'
                           name='city[city_contacts_attributes][<%= index %>][id]'
                           value="<%= contact.id %>">
                    <tr id='contact-<%= index %>'>
                      <td><%= index + 1 %></td>
                      <td>
                        <input type="text"
                               id='city_city_contacts_attributes_<%= index %>_name'
                               name='city[city_contacts_attributes][<%= index %>][name]'
                               placeholder='Address' value="<%= contact.name %>" class='form-control input-md'>
                      </td>
                      <td>
                        <input type="text"
                               id='city_city_contacts_attributes_<%= index %>_contact'
                               name='city[city_contacts_attributes][<%= index %>][contact]'
                               placeholder='Address' value="<%= contact.contact %>" class='form-control input-md'>
                      </td>
                    </tr>
                    <% end %>
                    <tr id='contact-<%= @city.city_contacts.length %>'></tr>
                    </tbody>
                  </table>
                </div>
                <button type="button" id='delete-contact' class="pull-right btn btn-default">Delete Contact</button>
                <button type="button" id="add-contact" class="pull-right btn btn-default">Add Contact</button>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :image_link, 'Background image: ', class: 'col-sm-2 control-label item' %>
            <div class="col-sm-10">
              <div class="city-file-upload btn btn-default">
                <span>Choose an image...</span>
                <%= f.file_field :image_link, multipart: true, id: 'city-file-upload-files'  %>
              </div>
              <input id="city-upload-files-info" placeholder="Nothing uploaded" disabled="disabled" />
            </div>
          </div>

          <div class="form-group">
            <%= label_tag(:files, 'Additional Files: ', class: 'col-sm-2 control-label item') %>
            <div class="col-sm-10">
              <div class="city-file-upload btn btn-default">
                <span>Choose one or more files...</span>
                <%= f.file_field :files, multipart: true, multiple: true, id: 'city-file-upload-image' %>
              </div>
              <input id="city-upload-image-info" placeholder="Nothing uploaded" disabled="disabled" />
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit 'Update', class: 'btn btn-primary' %>
              <button class="btn btn-default">
                <%= link_to('Cancel', "/cities/#{params[:id]}", :method => :get, :class => 'no-style') %>
              </button>
            </div>
          </div>
      <% end %>
    </div>

  </div>
</section>

<%= render partial: "layouts/footer" %>

recycling-server/app/views/cities/index.html.erb
<h1>Cities Search Results</h1>
<p>Find me in app/views/cities/index.html.erb</p>

recycling-server/app/views/cities/show.html.erb
<%= render partial: "layouts/nav", locals: {items: ["Categories", "Facilities", "Contact"], shouldShow: true, shouldShowDevelopers: false, useFixedNav: false} %>
<header class="city-header"
        style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(<%= asset_path "#{@city.image_link}" %>)">
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading"><%= @city.name %></h1>
      <div id="homeSubHeading">
        <span><%= @city.state %></span> | <span><%= @city.zipcode %></span>
      </div>
      <hr>
      <div id="homeDescription"><%= @city.description %></div>
      <h4>
        <i class="fa fa-external-link" aria-hidden="true" style="margin-right: 5px"></i>
        <a href="<%= @city.website %>">Goto Official Recycling Website</a>
      </h4>
    </div>
  </div>
</header>

<section class="city-slider-container">
  <div class="container category-title-container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Recyclable Categories</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="flexslider city-flexslider">
      <ul class="slides">
        <% @categories.each do |category| %>
          <li><div class="portfolio-box">
            <button id="category-<%= category.name.downcase %>" class="button-as-link">
              <%= image_tag "categories/thumbnails/#{category.image_link}", class: "img-responsive" %>
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-name">
                    <%= category.name %>
                  </div>
                </div>
              </div>
            </button>
          </div>

          </li>
        <% end %>
      </ul>
  </div>
</section>

<section class="city-category-container">
  <% @categories.each do |category| %>
  <div id="category-<%= category.name.downcase %>-details" class="category-details">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
      </thead>
      <% City.find_subcategories_by_id(@city.id, category.id).each_with_index do |subcategory, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= subcategory.name %></td>
            <td><%= subcategory.description %></td>
          </tr>
      <% end %>
    </table>
  </div>
  <% end %>
</section>

<section class="facility-map">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Facilities</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div id="map"></div>
</section>

<% if @filesJSON.size > 0 %>
<section class="city-files-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Additional Files</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="col-10 col-sm-10 col-md-10 col-offset-1 col-sm-offset-1 col-md-offset-1">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>#</th>
        <th>File</th>
      </tr>
      </thead>
      <% for i in 0..(@filesJSON.size-1) %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td>
              <% if Rails.env.production? %>
              <%= link_to @filesJSON[i].path.split('/')[-1], download_path(:file => @filesJSON[i].path) %>
              <% else %>
              <%= link_to @filesJSON[i].file.file.split('/')[-1], download_path(:file => @filesJSON[i].file.file) %>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</section>
<% end %>

<% if @city.city_contacts.length > 0 %>
<section class="city-contact-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Additional Contacts</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="col-10 col-sm-10 col-md-10 col-offset-1 col-sm-offset-1 col-md-offset-1">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email/Phone</th>
      </tr>
      </thead>
      <% @city.city_contacts.each_with_index do |contact, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= contact.name %></td>
            <td><%= contact.contact %></td>
          </tr>
      <% end %>
    </table>
  </div>
</section>
<% end %>

<% if (@contributor != nil) %>
<section class="city-files-container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Profile of Contributor</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="col-10 col-sm-8 col-md-6 col-offset-1 col-sm-offset-2 col-md-offset-3">
    <div class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10"><%= @contributor.name %></div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Job Title</label>
        <div class="col-sm-10"><%= @contributor.job_title %></div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10"><%= @contributor.email %></div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">City</label>
        <div class="col-sm-10"><%= @contributor.city %></div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">State</label>
        <div class="col-sm-10"><%= @contributor.state %></div>
      </div>
    </div>
  </div>
</section>
<% end %>

<%= render partial: "layouts/footer" %>